const BASE = ''

export const API_ROUTES = {
  auth: {
    login:   `${BASE}auth/login`,
    refresh: `${BASE}auth/refresh`,
    logout:  `${BASE}auth/logout`,
    me:      `${BASE}auth/me`,
  },
  authAttendance: {
    current: `${BASE}auth/staff/attendance/current`,
    clockIn: `${BASE}auth/staff/attendance/check-in`,
    clockOut: `${BASE}auth/staff/attendance/check-out`,
  },
  menu: {
    profile:     `${BASE}menu/profile`,
    categories:  `${BASE}menu/categories`,
    items:       `${BASE}menu/items`,
    item:        (id: string) => `${BASE}menu/items/${id}`,
  },
  adminMenu: {
    categories: `${BASE}admin/menu/categories`,
    category:   (id: string) => `${BASE}admin/menu/categories/${id}`,
    categoryHard: (id: string) => `${BASE}admin/menu/categories/${id}/hard`,
    items:       `${BASE}admin/menu/items`,
    item:        (id: string) => `${BASE}admin/menu/items/${id}`,
    bulkSale:    `${BASE}admin/menu/items/bulk-sale`,
    toggleOption: (id: string, optId: string) => `${BASE}admin/menu/items/${id}/options/${optId}/toggle`,
  },
  order: {
    root:       `${BASE}orders`,
    byId:       (id: string) => `${BASE}orders/${id}`,
    bySession:  (token: string) => `${BASE}orders/session/${token}`,
    byTable:    (tableId: string) => `${BASE}orders/table/${tableId}`,
    // POS Cart
    cart:       `${BASE}orders/cart`,
    cartItems:  `${BASE}orders/cart/items`,
    cartItem:   (cartItemId: string) => `${BASE}orders/cart/items/${cartItemId}`,
    tickets:    `${BASE}orders/tickets`,
    sessionOrder: `${BASE}orders/session`,
  },
  posSession: {
    openManual: (tableId: string) => `${BASE}sessions/open/manual/${tableId}`,
    close:      (token: string) => `${BASE}sessions/${token}/close`,
    extend:     (token: string) => `${BASE}sessions/${token}/extend`,
    byToken:    (token: string) => `${BASE}sessions/${token}`,
  },
  kds: {
    tickets:   `${BASE}kds/tickets`,
    ticket:    (id: string) => `${BASE}kds/tickets/${id}`,
    updateItem:(ticketId: string, itemId: string) => `${BASE}kds/tickets/${ticketId}/items/${itemId}`,
  },
  adminTable: {
    root:       `${BASE}admin/tables`,
    byId:       (id: string) => `${BASE}admin/tables/${id}`,
    generateQr: (id: string) => `${BASE}admin/tables/${id}/qr`,
    disableQr:  (id: string) => `${BASE}admin/tables/${id}/disable-qr`,
    toggleActive: (id: string) => `${BASE}admin/tables/${id}/toggle-active`,
    hardDelete: (id: string) => `${BASE}admin/tables/${id}/hard`,
  },
  table: {
    root:      `${BASE}tables`,
    byId:      (id: string) => `${BASE}tables/${id}`,
    cleanDone: (id: string) => `${BASE}tables/${id}/clean-done`,
    merge:     `${BASE}tables/merge`,
    transfer:  `${BASE}tables/transfer`,
  },
  report: {
    revenue:                `${BASE}reports/revenue`,
    topItems:               `${BASE}reports/top-items`,
    bySource:               `${BASE}reports/by-source`,
    byHour:                 `${BASE}reports/by-hour`,
    tables:                 `${BASE}reports/tables`,
    cashierShift:           `${BASE}reports/cashier-shift`,
    promotionEffectiveness: `${BASE}reports/promotion-effectiveness`,
    staffCalls:             `${BASE}reports/staff-calls`,
    kitchenPerformance:     `${BASE}reports/kitchen-performance`,     // 1.4: mới
    cancelledDrilldown:     `${BASE}reports/cancelled-drilldown`,     // 1.4: mới
    profitLoss:             `${BASE}reports/profit-loss`,
    inventoryVariance:      `${BASE}reports/inventory-variance`,
    inventoryVarianceExport: `${BASE}reports/inventory-variance/export`,
    purchaseSuggestions:    `${BASE}admin/inventory/reports/suggestions`,
    chefPerformance:        `${BASE}reports/kpi/kitchen`,
    serverPerformance:      `${BASE}reports/kpi/server`,
    categorySales:          `${BASE}reports/by-category`,
    staffTimesheet:         `${BASE}reports/timesheet`,
    reservations:           `${BASE}reports/reservations`,
  },
  promotion: {
    root:      `${BASE}admin/promotions`,
    byId:      (id: string) => `${BASE}admin/promotions/${id}`,
    hardDelete:(id: string) => `${BASE}admin/promotions/${id}/hard`,
    toggle:    (id: string) => `${BASE}admin/promotions/${id}/toggle`,
    validate:  `${BASE}promotions/validate`,
    flashSale: `${BASE}admin/promotions/flash-sale`,
  },
  adminStaff: {
    root:   `${BASE}admin/staff`,
    byId:   (id: string) => `${BASE}admin/staff/${id}`,
    toggle: (id: string) => `${BASE}admin/staff/${id}/toggle`,
    shifts: `${BASE}auth/admin/staff/shifts`,
    schedules: `${BASE}auth/admin/staff/schedules`,
    assign: `${BASE}auth/admin/staff/schedules/assign`,
    attendance: `${BASE}auth/admin/staff/attendance`,
    attendanceSummary: `${BASE}auth/admin/staff/attendance/summary`,
  },
  ai: {
    customerChat: `${BASE}customer/ai/chat`,
    adminChat:    `${BASE}admin/ai/chat`, // Admin AI Agent
  },
  inventory: {
    uoms:          `${BASE}admin/inventory/uoms`,
    uom:           (id: string) => `${BASE}admin/inventory/uoms/${id}`,
    uomsSearch:    `${BASE}admin/inventory/uoms/search`,
    categories:    `${BASE}admin/inventory/categories`,
    category:      (id: string) => `${BASE}admin/inventory/categories/${id}`,
    categoriesSearch: `${BASE}admin/inventory/categories/search`,
    suppliers:     `${BASE}admin/inventory/suppliers`,
    supplier:      (id: string) => `${BASE}admin/inventory/suppliers/${id}`,
    supplierToggle:(id: string) => `${BASE}admin/inventory/suppliers/${id}/toggle`,
    items:         `${BASE}admin/inventory/items`,
    item:          (id: string) => `${BASE}admin/inventory/items/${id}`,
    itemToggle:    (id: string) => `${BASE}admin/inventory/items/${id}/toggle`,
    itemConversions: (itemId: string) => `${BASE}admin/inventory/items/${itemId}/conversions`,
    conversions:   `${BASE}admin/inventory/conversions`,
    conversion:    (id: string) => `${BASE}admin/inventory/conversions/${id}`,
    recipes:       `${BASE}admin/inventory/recipes`,
    recipeBySaleItem: (saleItemId: string) => `${BASE}admin/inventory/recipes/by-sale-item/${saleItemId}`,
    recipeByModifier: (modifierId: string) => `${BASE}admin/inventory/recipes/by-modifier/${modifierId}`,
    recipe:        (id: string) => `${BASE}admin/inventory/recipes/${id}`,
    po:            `${BASE}admin/inventory/purchase-orders`,
    poById:        (id: string) => `${BASE}admin/inventory/purchase-orders/${id}`,
    poConfirm:     (id: string) => `${BASE}admin/inventory/purchase-orders/${id}/confirm`,
    poReceive:     (id: string) => `${BASE}admin/inventory/purchase-orders/${id}/receive`,
    poForceComplete: (id: string) => `${BASE}admin/inventory/purchase-orders/${id}/force-complete`,
    poCancel:      (id: string) => `${BASE}admin/inventory/purchase-orders/${id}/cancel`,
    stocktake:     `${BASE}admin/inventory/stocktakes`,
    stocktakeById: (id: string) => `${BASE}admin/inventory/stocktakes/${id}`,
    stocktakeFinalize: (id: string) => `${BASE}admin/inventory/stocktakes/${id}/complete`,
    stocktakeCancel: (id: string) => `${BASE}admin/inventory/stocktakes/${id}/cancel`,
    transactions:  `${BASE}admin/inventory/transactions`,
    reportLowStock:`${BASE}admin/inventory/reports/low-stock`,
    reportVariance:`${BASE}admin/inventory/reports/variance`,
    reportExpiring:`${BASE}admin/inventory/reports/expiring`,
    reportDashboard:`${BASE}admin/inventory/reports/dashboard-summary`,
    reportTrend:`${BASE}admin/inventory/reports/trend`,
    locations:     `${BASE}admin/inventory/locations`,
    location:      (id: string) => `${BASE}admin/inventory/locations/${id}`,
    locationToggle:(id: string) => `${BASE}admin/inventory/locations/${id}/toggle`,
  },
} as const
