export const ROUTES = {
  login:        '/login',
  unauthorized: '/unauthorized',
  pos: {
    tables:      '/pos/tables',
    orderEntry:  '/pos/orders/new/:tableId?',
    menu:        '/pos/menu', // Màn hình chọn món trực tiếp
    orderDetail: '/pos/orders/:tableId',
    payment:     '/pos/payment/:tableId',
    reports:     '/pos/reports',
    order:       (id: string) => `/pos/orders/${id}`,
  },
  kds:      '/kds',
  server:   '/server',
  admin: {
    root:       '/admin',
    dashboard:  '/admin/dashboard',
    menu:       '/admin/menu',
    menuCreate: '/admin/menu/new',
    menuEdit:   '/admin/menu/:id/edit',
    promotions:      '/admin/promotions',
    promotionCreate: '/admin/promotions/new',
    promotionEdit:   '/admin/promotions/:id/edit',
    tables:     '/admin/tables',
    staff:      '/admin/staff',
    reports:    '/admin/reports',
    orders:     '/admin/orders',
    settings:   '/admin/settings',
  },
  customer: {
    root:    '/',
    menu:    '/menu',
    status:  '/order-status',
    payment: '/payment',
  },
} as const
