export const ROUTES = {
  login:        '/login',
  unauthorized: '/unauthorized',
  pos: {
    tables:      '/pos/tables',
    reservations:'/pos/reservations',
    orderEntry:  '/pos/orders/new/:tableId?',
    menu:        '/pos/menu', // Màn hình chọn món trực tiếp
    orderDetail: '/pos/orders/:tableId',
    payment:     '/pos/payment/:tableId',
    reports:     '/pos/reports',
    order:       (id: string) => `/pos/orders/${id}`,
  },
  kds:      '/kds',
  server:   '/server',
  admin: {
    root:       '/admin',
    dashboard:  '/admin/dashboard',
    reservations: '/admin/reservations',
    menu:       '/admin/menu',
    menuCreate: '/admin/menu/new',
    menuEdit:   '/admin/menu/:id/edit',
    promotions:      '/admin/promotions',
    promotionCreate: '/admin/promotions/new',
    promotionEdit:   '/admin/promotions/:id/edit',
    tables:     '/admin/tables',
    staff:      '/admin/staff',
    reports:    '/admin/reports',
    orders:     '/admin/orders',
    orderDetail:'/admin/orders/:id',
    settings:   '/admin/settings',
    inventory:  '/admin/inventory',
  },
  customer: {
    root:        '/',
    booking:     '/booking',
    menu:        '/menu',
    status:      '/order-status',
    payment:     '/payment',
    bookingMenu: '/booking/menu',
  },
} as const

